# Generated by Django 2.2.24 on 2023-01-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20230102_0956'),
    ]

    operations = [
    ]
