# Generated by Django 4.1.5 on 2023-01-03 06:08

from django.conf import settings
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0009_flat_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="owner_pure_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="has_balcony",
            field=models.BooleanField(
                db_index=True, null=True, verbose_name="Наличие балкона"
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайки",
            ),
        ),
    ]
