# Generated by Django 2.2.24 on 2023-01-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20230102_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет'), (None, 'Неизвестно')], verbose_name='Новостройка'),
        ),
    ]
