# Generated by Django 4.1.5 on 2023-01-03 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0011_auto_20230103_0949"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flat",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайки",
            ),
        ),
    ]
