# Generated by Django 4.1.5 on 2023-01-03 07:20

import phonenumbers
from django.db import migrations

def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for number in flats.iterator():
        normal_phone = phonenumbers.parse(number.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(normal_phone):
            number.owner_pure_phone = normal_phone
            number.save()


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0012_alter_flat_likes"),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers)
    ]
