# Generated by Django 4.1.5 on 2023-01-03 22:01

from django.db import migrations


def migrate_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        owner_flats = Owner.objects.filter(name = flat.owner, owners_phonenumber = flat.owners_phonenumber)
        flat.flat_owners.set(owner_flats)


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0015_auto_20230104_0028"),
    ]

    operations = [
        migrations.RunPython(migrate_owners)
    ]
