# Generated by Django 2.2.24 on 2023-01-02 05:54

from django.db import migrations

def set_new_bilding():
        Flat.Objects.filter(construction_year__gte = 2005).update(new_building = True)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(set_new_bilding)
    ]
